version: 2.1

orbs:
  maven: circleci/maven@1.0.2

executors:
  ojdk11:
    docker:
      - image: cimg/openjdk:11.0
workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
        executor: ojdk11
